#!/bin/bash

#2.PIEMĒRS SASKAITA TRĪS SKAITĻUS UN IZDALA AR brīvi izvēlētu skaitli
read -p "Ievadi pirmo skaitli : " n1
read -p "Ievadi otro skaitli :  " n2
read -p "Ievadi trešo skaitli : " n3
read -p "Ievadi skaitli ar kuru vēlies dalīt : " n4
# dolara zīme un dubulta iekava, tad rezultātu saskaita kopā!
var=$((($n1+$n2+$n3)/$n4))
rez=$((($n1+$n2+$n3%n3)*10))
echo "$var.$rez"
