#!/bin/bash
read -p "Ievadi pirmo skaitli : " n1
read -p "Ievadi otro skaitli :  " n2
read -p "Ievadi trešo skaitli : " n3
if (( $n1 > $n2 ))  && (( $n1 > $n3 )) && (( $n2 > $n3 ))
then 
echo -e "MAX:$n1\nMIN:$n3"
elif (( $n2 > $n1 )) && (( $n2 > $n3 )) && (( $n1 > $n3 )) 
then
echo -e "MAX:$n2\n$MIN:$n3"
elif (( $n3 > $n2 )) && (( $n3 > $n1 )) && (( $n2 > $n1 ))
then
echo -e "MAX:$n3\nMIN:$n1"
elif (( $n3 > $n2 )) && (( $n3 > $n1 )) && (( $n1 > $n2 ))
then
echo -e "MAX:$n3\nMIN:$n2"
elif (( $n1 > $n2 )) && (( $n1 > $n3 )) && (( $n3 > $n2 ))
then
echo -e "MAX:$n1\nMIN:$n2"
elif (( $n2 > $n1 )) && (( $n2 > $n3 )) && (( $n3 > $n1 ))
then
echo -e "MAX:$n2\nMIN:$n1"
elif (( $n2 > $n1 )) && (( $n2 > $n3 )) && (( $n1 < $n3 ))
then
echo -e "MAX:$n2\nMIN:$n1"

fi


