function createfigure(X1, ymatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  stairs x
%  YMATRIX1:  stairs matrix data

%  Auto-generated by MATLAB on 12-Feb-2018 09:30:29

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to stairs
stairs1 = stairs(X1,ymatrix1);
set(stairs1(1),'DisplayName','sinusoida');
set(stairs1(2),'DisplayName','cosinusoida','LineWidth',1,'LineStyle','-.',...
    'Color',[1 0 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','baseline',...
    'String','\leftarrow sinusoida',...
    'Position',[0.341121495327103 0.00557103064066844 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','baseline','String','x_m',...
    'Position',[0.31619937694704 -0.479108635097493 0]);

% Create text
text('Parent',axes1,'VerticalAlignment','baseline','String','x^2',...
    'Position',[0.129283489096573 0.64066852367688 0]);

% Create xlabel
xlabel('\Omega');

% Create title
title('Grafiks');

% Create ylabel
ylabel('U,V');

box(axes1,'on');
% Create legend
legend(axes1,'show');

