#!/usr/bin/python
# -*- coding: utf-8 -*-

print "Tūkstošiem lausku uz ceļa \vPasaulē, kur eņģeļa vairs nav neviena \vBrūces un asaras ir tikai sīkums \vAr nelabo tas kā simboliski parakstīts līgums.\n" 
print "\t\t\t\t\t\t\t\tAkli taustīdamās uz priekšu,"
print "\t\t\tŠķiet, ka sāpēs es reiz kliegšu,"
print "Vietā, kur dzimst katra cilvēka mokas,"

